import { Interval } from '../types'

export default {
  'Chormatic': [
    Interval.U,
    Interval.m2,
    Interval.M2,
    Interval.m3,
    Interval.M3,
    Interval.P4,
    Interval.TT,
    Interval.P5,
    Interval.m6,
    Interval.M6,
    Interval.m7,
    Interval.M7,
    Interval.Oct,
  ],
  'Major': [ // Ionian mode
    Interval.U,
    Interval.M2,
    Interval.M3,
    Interval.P4,
    Interval.P5,
    Interval.M6,
    Interval.M7,
    Interval.Oct,
  ],
  'Natural Minor': [ // Aeolian mode
    Interval.U,
    Interval.M2,
    Interval.m3,
    Interval.P4,
    Interval.P5,
    Interval.m6,
    Interval.m7,
    Interval.Oct,
  ],
  'Harmonic Minor': [ // Aeolian #7 scale
    Interval.U,
    Interval.M2,
    Interval.m3,
    Interval.P4,
    Interval.P5,
    Interval.m6,
    Interval.M7,
    Interval.Oct,
  ],
  'Melodic Minor': [
    Interval.U,
    Interval.M2,
    Interval.m3,
    Interval.P4,
    Interval.P5,
    Interval.M6,
    Interval.M7,
    Interval.Oct,
  ],
}